name: Monero Node Scanner

on:
  schedule:
    # Run at specific times (midnight, 6am, 12pm, 6pm UTC)
    - cron: '0 0,6,12,18 * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install Tor
        run: |
          sudo apt-get update
          sudo apt-get install -y tor
          sudo service tor start
          # Verify Tor is running
          sleep 5  # Give Tor time to start
          netstat -tulpn | grep 9050 || echo "Warning: Tor might not be running on port 9050"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests[socks] PySocks python-dotenv

      - name: Run node scanner
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        run: |
          # Create necessary directories
          mkdir -p data
          
          # Run the scanner once
          python main.py --scan-once

      - name: Archive results
        uses: actions/upload-artifact@v3
        with:
          name: scan-results
          path: data/latest_scan.json
          retention-days: 7

      - name: Commit and push if there are changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Only commit changes to data directory
          git add -A data/
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update node scan data [skip ci]"
            git push
          fi